from __future__ import annotations

# Registry built only from products, tools and processes explicitly identified
# in the reviewed Arus PrintAssist scope. The router does not import product rules.
PRODUCT_ENTITY_REGISTRY = {
    "papercut_mf": {"canonical_name":"PaperCut MF","aliases":["papercut mf","papercut"],"vendor":"papercut","entity_type":"software_platform","domain_area":"print_management","in_scope":True,"related_entities":["papercut_ng","papercut_hive","hp_oxp"],"common_intents":["conceptual","requirements","procedural","troubleshooting"],"retrieval_hints":{"vendor":"papercut","product":"papercut_mf"}},
    "papercut_ng": {"canonical_name":"PaperCut NG","aliases":["papercut ng"],"vendor":"papercut","entity_type":"software_platform","domain_area":"print_management","in_scope":True,"related_entities":["papercut_mf"],"common_intents":["conceptual","requirements","procedural","troubleshooting"],"retrieval_hints":{"vendor":"papercut","product":"papercut_ng"}},
    "papercut_hive": {"canonical_name":"PaperCut Hive","aliases":["papercut hive","hive"],"vendor":"papercut","entity_type":"cloud_print_platform","domain_area":"print_management","in_scope":True,"related_entities":["papercut_mf","papercut_pocket"],"common_intents":["conceptual","requirements","procedural","troubleshooting"],"retrieval_hints":{"vendor":"papercut","product":"papercut_hive"}},
    "papercut_pocket": {"canonical_name":"PaperCut Pocket","aliases":["papercut pocket","pocket"],"vendor":"papercut","entity_type":"cloud_print_platform","domain_area":"print_management","in_scope":True,"related_entities":["papercut_hive"],"common_intents":["conceptual","procedural","troubleshooting"],"retrieval_hints":{"vendor":"papercut","product":"papercut_pocket"}},
    "hp_sds": {"canonical_name":"HP Smart Device Services","aliases":["hp smart device services","hp sds","sds"],"vendor":"hp","entity_type":"device_service_platform","domain_area":"device_management","in_scope":True,"related_entities":["hp_sds_monitor","hp_sds_dca","jamc"],"common_intents":["conceptual","requirements","procedural","troubleshooting","architecture"],"retrieval_hints":{"vendor":"hp","product":"sds"}},
    "hp_sds_monitor": {"canonical_name":"HP SDS Monitor","aliases":["hp sds monitor","sds monitor"],"vendor":"hp","entity_type":"software_component","domain_area":"device_management","in_scope":True,"related_entities":["hp_sds"],"common_intents":["conceptual","requirements","procedural","troubleshooting"],"retrieval_hints":{"vendor":"hp","product":"sds","component":"monitor"}},
    "hp_sds_dca": {"canonical_name":"HP SDS DCA","aliases":["hp sds dca","sds dca","dca"],"vendor":"hp","entity_type":"software_component","domain_area":"device_management","in_scope":True,"related_entities":["hp_sds"],"common_intents":["conceptual","requirements","procedural","troubleshooting"],"retrieval_hints":{"vendor":"hp","product":"sds","component":"dca"}},
    "jamc": {"canonical_name":"JAMC","aliases":["jamc"],"vendor":"hp","entity_type":"software_component","domain_area":"device_management","in_scope":True,"related_entities":["hp_sds"],"common_intents":["conceptual","requirements","procedural","troubleshooting"],"retrieval_hints":{"vendor":"hp","product":"sds","component":"jamc"}},
    "hp_web_jetadmin": {"canonical_name":"HP Web Jetadmin","aliases":["hp web jetadmin","web jetadmin","web jet admin","wja"],"vendor":"hp","entity_type":"device_management_platform","domain_area":"device_management","in_scope":True,"related_entities":[],"common_intents":["conceptual","requirements","procedural","troubleshooting"],"retrieval_hints":{"vendor":"hp","product":"web_jetadmin"}},
    "hp_access_control": {"canonical_name":"HP Access Control","aliases":["hp access control","hp ac","hac"],"vendor":"hp","entity_type":"print_security_platform","domain_area":"print_management","in_scope":True,"related_entities":["hp_oxp"],"common_intents":["conceptual","requirements","procedural","troubleshooting"],"retrieval_hints":{"vendor":"hp","product":"hp_access_control"}},
    "hp_oxp": {"canonical_name":"HP OXP","aliases":["hp oxp","oxp"],"vendor":"hp","entity_type":"embedded_platform","domain_area":"embedded_devices","in_scope":True,"related_entities":["hp_access_control","papercut_mf"],"common_intents":["conceptual","requirements","procedural","architecture","troubleshooting"],"retrieval_hints":{"vendor":"hp","component":"oxp"}},
    "gav_tracking": {"canonical_name":"GAV Tracking","aliases":["gav tracking","gav"],"vendor":"gav","entity_type":"print_tracking_platform","domain_area":"print_management","in_scope":True,"related_entities":[],"common_intents":["conceptual","requirements","procedural","troubleshooting"],"retrieval_hints":{"vendor":"gav","product":"gav_tracking"}},
    "print_evolve": {"canonical_name":"Print Evolve","aliases":["print evolve"],"vendor":"arus_internal","entity_type":"service_platform","domain_area":"print_service","in_scope":True,"related_entities":[],"common_intents":["conceptual","procedural","troubleshooting","architecture"],"retrieval_hints":{"product":"print_evolve"}},
    "mfpsecure": {"canonical_name":"MFPsecure","aliases":["mfpsecure","mfp secure"],"vendor":"arus_internal","entity_type":"print_security_platform","domain_area":"print_security","in_scope":True,"related_entities":[],"common_intents":["conceptual","procedural","troubleshooting","architecture"],"retrieval_hints":{"product":"mfpsecure"}},
    "epson_remote_services": {"canonical_name":"Epson Remote Services","aliases":["epson remote services","ers"],"vendor":"epson","entity_type":"device_service_platform","domain_area":"device_management","in_scope":True,"related_entities":["epson_print_admin"],"common_intents":["conceptual","requirements","procedural","troubleshooting"],"retrieval_hints":{"vendor":"epson","product":"epson_remote_services"}},
    "epson_print_admin": {"canonical_name":"Epson Print Admin","aliases":["epson print admin","epa"],"vendor":"epson","entity_type":"print_management_platform","domain_area":"print_management","in_scope":True,"related_entities":["epson_remote_services"],"common_intents":["conceptual","requirements","procedural","troubleshooting"],"retrieval_hints":{"vendor":"epson","product":"epson_print_admin"}},
    "hp_printers": {"canonical_name":"Impresoras HP","aliases":["impresora hp","impresoras hp","multifuncional hp","mfp hp","hp laserjet","hp officejet","hp pagewide"],"vendor":"hp","entity_type":"device_family","domain_area":"printing_devices","in_scope":True,"related_entities":[],"common_intents":["conceptual","procedural","troubleshooting","warranty"],"retrieval_hints":{"vendor":"hp","product":"hp_printers"}},
    "epson_printers": {"canonical_name":"Impresoras Epson","aliases":["impresora epson","impresoras epson","multifuncional epson","epson ecotank","epson workforce"],"vendor":"epson","entity_type":"device_family","domain_area":"printing_devices","in_scope":True,"related_entities":[],"common_intents":["conceptual","procedural","troubleshooting","warranty"],"retrieval_hints":{"vendor":"epson","product":"epson_printers"}},
    "da_arus": {"canonical_name":"DA Arus","aliases":["da arus"],"vendor":"arus_internal","entity_type":"internal_support_collection","domain_area":"print_service","in_scope":True,"related_entities":[],"common_intents":["conceptual","procedural","operational"],"retrieval_hints":{"product":"sanitized_support_assets"}},
    "mipa_agent": {"canonical_name":"Agente MIPA","aliases":["agente mipa","mipa agent","mipa"],"vendor":"arus_internal","entity_type":"software_agent","domain_area":"print_service","in_scope":True,"related_entities":[],"common_intents":["conceptual","procedural","troubleshooting"],"retrieval_hints":{"product":"mipa_agent"}},
    "dashboard_simp": {"canonical_name":"Dashboard SIMP","aliases":["dashboard simp"],"vendor":"arus_internal","entity_type":"operational_platform","domain_area":"print_service","in_scope":True,"related_entities":[],"common_intents":["conceptual","procedural","operational"],"retrieval_hints":{"product":"dashboard_simp"}},
}

PROCESS_ENTITY_REGISTRY = {
    "control_consumables": {"canonical_name":"Control de consumibles","aliases":["control de consumibles","control de suministros","gestión de consumibles","gestion de consumibles"],"entity_type":"service_process","domain_area":"operational_process","in_scope":True,"common_intents":["procedural","operational"]},
    "asset_management": {"canonical_name":"Gestión de activos","aliases":["gestion de activos","gestión de activos","activos de impresion","activos de impresión"],"entity_type":"service_process","domain_area":"operational_process","in_scope":True,"common_intents":["procedural","operational"]},
    "supplies_warranty": {"canonical_name":"Garantía de suministros","aliases":["garantia de suministros","garantía de suministros","garantia de consumibles","garantía de consumibles"],"entity_type":"service_process","domain_area":"warranty","in_scope":True,"common_intents":["warranty","procedural"]},
    "equipment_warranty": {"canonical_name":"Garantía de equipos","aliases":["garantia de equipos","garantía de equipos","garantia de impresoras","garantía de impresoras"],"entity_type":"service_process","domain_area":"warranty","in_scope":True,"common_intents":["warranty","procedural"]},
    "billing_distribution": {"canonical_name":"Distribución de facturación","aliases":["distribucion de facturacion","distribución de facturación","facturacion con template","facturación con template","distribucion de costos","distribución de costos"],"entity_type":"service_process","domain_area":"billing","in_scope":True,"common_intents":["procedural","operational"]},
    "prefactura_simp": {"canonical_name":"Prefactura SIMP","aliases":["prefactura simp","pre-factura simp","prefactura"],"entity_type":"service_process","domain_area":"billing","in_scope":True,"common_intents":["procedural","operational"]},
    "pin_printing": {"canonical_name":"PIN de impresión","aliases":["pin de impresion","pin de impresión","codigo de impresion","código de impresión","autogestion pin impresion","autogestión pin impresión"],"entity_type":"service_process","domain_area":"authentication","in_scope":True,"common_intents":["procedural","troubleshooting"]},
    "scan_to_folder": {"canonical_name":"Escaneo a carpeta","aliases":["escaneo a carpeta","scan to folder","escanear a carpeta"],"entity_type":"service_process","domain_area":"scanning","in_scope":True,"common_intents":["procedural","troubleshooting"]},
    "printer_installation": {"canonical_name":"Instalación de impresoras","aliases":["instalacion de impresora","instalación de impresora","agregar una impresora","instalar impresora"],"entity_type":"service_process","domain_area":"printing_devices","in_scope":True,"common_intents":["procedural","troubleshooting"]},
    "firmware_management": {"canonical_name":"Gestión de firmware","aliases":["actualizacion de firmware","actualización de firmware","firmware de impresora","gestion de firmware","gestión de firmware"],"entity_type":"service_process","domain_area":"device_management","in_scope":True,"common_intents":["procedural","troubleshooting"]},
    "mobile_printing": {"canonical_name":"Impresión móvil","aliases":["impresion movil","impresión móvil","mobile printing","impresion desde celular","impresión desde celular"],"entity_type":"service_process","domain_area":"print_service","in_scope":True,"common_intents":["conceptual","procedural","troubleshooting"]},
    "incident_escalation": {"canonical_name":"Escalamiento de incidentes","aliases":["escalamiento de incidente","escalamiento de incidentes","escalar el caso","escalar incidente"],"entity_type":"support_process","domain_area":"support","in_scope":True,"common_intents":["escalation"]},
}

def build_alias_index(registry: dict) -> dict[str,str]:
    result = {}
    for entity_id, item in registry.items():
        for alias in [item.get("canonical_name","")] + list(item.get("aliases") or []):
            if alias: result[str(alias).lower()] = entity_id
    return result

PRODUCT_ALIAS_INDEX = build_alias_index(PRODUCT_ENTITY_REGISTRY)
PROCESS_ALIAS_INDEX = build_alias_index(PROCESS_ENTITY_REGISTRY)
