from __future__ import annotations
import json
class ResponseComposer:
 def __init__(self,gateway=None,max_tokens=420):self.gateway=gateway;self.max_tokens=max(300,min(560,int(max_tokens)))
 def _product(self,state):
  p=getattr(getattr(state,"active_topic",None),"products",[]) or [];return p[0].canonical_name if p else "el tema consultado"
 def compose_conversation(self,message,decision,state):
  if self.gateway is None:return {"mode":"conversation_pending","text":decision.clarification_question or "¿En qué puedo ayudarte?","citations":[],"knowledge_used":False}
  from app.llm_gateway.models import LLMRequest
  payload={"message":message,"canonical_state":state.to_dict(),"instructions":["No preguntes nuevamente algo que ya aparezca en el mensaje actual o el estado.","Una respuesta breve debe completar la aclaración anterior, no borrar la solicitud técnica.","Pregunta solo un dato imprescindible ausente."]};res=self.gateway.complete(LLMRequest([{"role":"system","content":"Responde en español, de forma natural y breve. No inventes hechos ni campos."},{"role":"user","content":json.dumps(payload,ensure_ascii=False,default=str)}],"agent_core_v2_conversation_response",220,0.,None))
  if not res.ok or not str(res.text or "").strip() or res.finish_reason=="length":return {"mode":"safe_conversation_fallback","text":decision.clarification_question or "Necesito un dato adicional para continuar sin asumir información.","citations":[],"knowledge_used":False,"fallback_reason":"response_truncated" if res.finish_reason=="length" else "provider_error"}
  return {"mode":"natural_conversation","text":res.text.strip(),"citations":[],"knowledge_used":False,"provider":res.provider,"model":res.model,"usage":res.usage,"finish_reason":res.finish_reason}
 def compose(self,query,decision,state,evidence):
  citable=list(evidence.get("citable") or []);unassessed=list(evidence.get("unassessed") or []);case=state.technical_case
  docs=[{"id":x.get("id"),"title":x.get("title"),"url":x.get("url"),"page":(x.get("metadata") or {}).get("page_label") or (x.get("metadata") or {}).get("page"),"citation_scope":x.get("citation_scope"),"supported_claims":(x.get("semantic_assessment") or {}).get("supported_claims") or [],"approved_excerpt":str(x.get("text") or "")[:1200]} for x in citable]
  payload={"current_request":query,"current_intent":decision.intent,"product":self._product(state),"case":{"symptoms":list(case.symptoms),"affected_scope":case.affected_scope,"attempts":[{"action":a.action,"result":a.result} for a in case.attempts]},"approved_documentation":docs,"unassessed_count":len(unassessed),"instructions":["Responde exclusivamente la solicitud actual.","Usa cualquier detalle explícito visible en approved_excerpt que responda la solicitud, sin exceder el alcance de la fuente.","No afirmes que el extracto carece de detalles si esos detalles aparecen literalmente en approved_excerpt.","Distingue evidencia documentada de orientación complementaria.","No inventes pasos, rutas, puertos, credenciales ni compatibilidades.","Si la fuente solo indica dónde obtener un procedimiento, explica esa limitación y conserva la orientación documentada.","Responde entre 90 y 240 palabras y cita las fuentes por título, no mediante nombres internos de campos."]}
  if self.gateway is None:return self._safe(state,unassessed,"gateway_not_configured")
  from app.llm_gateway.models import LLMRequest
  res=self.gateway.complete(LLMRequest([{"role":"system","content":"Eres un agente documental. La evidencia aprobada incluye afirmaciones y extractos; aprovecha ambos con atribución estricta."},{"role":"user","content":json.dumps(payload,ensure_ascii=False,default=str)}],"agent_core_v2_answer",self.max_tokens,0.,None))
  if not res.ok or not str(res.text or "").strip() or res.finish_reason=="length":return self._safe(state,unassessed,"response_truncated" if res.finish_reason=="length" else "provider_error")
  return {"mode":"grounded" if citable else "guarded_internal_knowledge","text":res.text.strip(),"citations":[{"id":x.get("id"),"title":x.get("title"),"url":x.get("url"),"page":(x.get("metadata") or {}).get("page_label") or (x.get("metadata") or {}).get("page")} for x in citable],"knowledge_used":not bool(citable) or "Orientación complementaria" in res.text,"unassessed_sources":[x.get("id") for x in unassessed],"provider":res.provider,"model":res.model,"usage":res.usage,"finish_reason":res.finish_reason}
 def _safe(self,state,unassessed,reason):
  return {"mode":"safe_hybrid_fallback","text":"No pude completar una respuesta documental confiable con la evidencia evaluada. Puedo continuar con una orientación general segura o preparar el escalamiento, sin presentar supuestos como documentación.","citations":[],"knowledge_used":True,"unassessed_sources":[x.get("id") for x in unassessed],"fallback_reason":reason}
